### ISSUE TITLE
无法打开clash管理页面

### ISSUE THREAD

**Issue by inetkiller** [learnhard-cn/vClash#10]
环境信息：
路由器：华硕AC86U
固件版本：384

已确认clash成功安装，并成功启动，进路由器能看到启动了9090，3333等端口

现象：点击clash面板按钮，提示404（很奇怪访问的地址是不带9090端口的）
直接访问clash面板按钮上面提示的带9090端口的地址，提示未认证，9090端口看起来像是一个restful api，不是用来选择节点的web控制台

求大佬解惑

**Comment by luckydzp** [comment]
我和题主有相同的问题。
另外，我启动成功了，但是电脑上网没法科学。
在电脑上使用tanpopo订阅，是正常的。
![image](https://user-images.githubusercontent.com/3041197/162357341-c32e4349-2a53-409a-8da8-3ff9838eacf7.png)
![image](https://user-images.githubusercontent.com/3041197/162357375-754cfb21-4664-4c62-9def-516388e68081.png)![image](https://user-images.githubusercontent.com/3041197/162357503-176d4392-cb81-41f8-bc51-125dff8b0775.png)

**Comment by luckydzp** [comment]
![image](https://user-images.githubusercontent.com/3041197/162357675-23996590-6cc5-4fd0-a9cb-dc1173732645.png)
![image](https://user-images.githubusercontent.com/3041197/162357709-9f6178a0-0ae8-4a19-8ec1-905a98c15b35.png)
![image](https://user-images.githubusercontent.com/3041197/162357742-a40f7464-06c3-4692-b2fe-6b8030c80bb0.png)

**Comment by luckydzp** [comment]
我和题主有相同的问题。
另外，我启动成功了，但是电脑上网没法科学。
在电脑上使用tanpopo订阅，是正常的。
一切都显示正常。但没法科学上网。另外管理面板也打不开，点击跳转不会加9090端口，手动输入路由地址加9090端口显示未认证

**Comment by inetkiller** [comment]
@luckydzp 我找到解决办法了，执行 mkdir /var/wwwext/ && cp -r /koolshare/clash/dashboard/ /var/wwwext/

**Comment by Awkee** [comment]
执行命令 `mkdir /www/ext/`   就可以了，之后启动脚本会自动创建软链接到  /koolshare/clash/dashboard/ 目录的。
