### ISSUE TITLE
384

### ISSUE THREAD

**Issue by BevisssLiu** [learnhard-cn/vClash#12]
`asus@RT-AC66U_B1-2698:/tmp# sh clash/install.sh`
`2022年05月01日22:14:12:clash: 很抱歉！本插件只支持 KS梅林固件的380和386版本!而您的固件版本为: 384`

**Comment by Awkee** [comment]
你使用的vClash是那个版本呀？最新版是release目录下的clash.tar.gz文件。你试试看吧。
