### ISSUE TITLE
能出armv7l吗

### ISSUE THREAD

**Issue by zhangbo1201** [learnhard-cn/vClash#15]
糟糕！ 不支持 armv7l 平台呀！ 您的路由器型号:TUF-AX3000_V2 ,固件类型： koolshare官改固件 ,固件版本： ,给开发者反馈一下这个问题吧！

**Comment by Awkee** [comment]
支持armv7l平台的呀, 请把安装过程日志内容全部帖出来才能看到哪里出错了,安装包是从哪个地址获取的?
