### ISSUE TITLE
ks 380 平台报错

### ISSUE THREAD

**Issue by maxmonkey950** [learnhard-cn/vClash#17]
【2022年07月30日 01:39:13】: ====================== step 1 ===========================
【2022年07月30日 01:39:13】: 开启软件离线安装！
【2022年07月30日 01:39:13】: /tmp目录下检测到上传的离线安装包clash.tar.gz，大小：18.8M
【2022年07月30日 01:39:13】: 尝试解压离线安装包离线安装包
【2022年07月30日 01:39:15】: 解压完成！
【2022年07月30日 01:39:15】: 准备安装clash插件！
【2022年07月30日 01:39:15】: 找到安装脚本！
【2022年07月30日 01:39:15】: 运行安装脚本...
【2022年07月30日 01:39:15】: ====================== step 2 ===========================
2022年07月30日01:39:16:clash: Clash版科学上网插件开始安装！
2022年07月30日01:39:17:clash: CPU架构: armv5 符合安装要求!
2022年07月30日01:39:17:clash: KoolShare目录存在，继续检测固件平台支持!
2022年07月30日01:39:17:clash: 糟糕！ 不支持 armv7l 平台呀！ 您的路由器型号: ,固件类型：  ,固件版本：380 ,请将安装过程日志内容(上面的所有内容)复制好后反馈给开发者,以便于帮您找到安装失败原因！反馈地址: https://github.com/learnhard-cn/vClash/issues/
【2022年07月30日 01:39:17】: 因为clash插件安装失败！退出离线安装！
【2022年07月30日 01:39:17】: ======================== end ============================
 
XU6J03M6

下载地址如下：
https://github.com/learnhard-cn/vClash/raw/ksmerlin386/release/clash.tar.gz

**Comment by maxmonkey950** [comment]
设备是r6300v2

**Comment by Awkee** [comment]
你应该选择380版本试试，386版本无法在 380固件上运行的。
