### ISSUE TITLE
clash进程启动失败

### ISSUE THREAD

**Issue by AltriaPendrag0n** [learnhard-cn/vClash#20]
**Bug描述**
插件启动失败，报错如下：
2022年09月01日21:21:54: 启动配置文件 /koolshare/clash/config.yaml : 检测完毕!
2022年09月01日21:21:57: clash -d /koolshare/clash/ 启动失败! 执行失败原因如下:
/koolshare/bin/clash: line 1: syntax error: unexpected word (expecting ")")

**Bug重现**
描述触发Bug的步骤:
1. 在软件中心打开clash插件
2. 点击开启clash按钮
3. 启动失败并报错

机型：ASUS RT-AX88U
梅林版本：梅林改版 386.5_2
插件版本：vv2.2.13
浏览器：MacOS版Chrome

**Comment by Awkee** [comment]
可能是这个原因：clash程序架构不对，是否升级过clash版本？

可以阅读一下[wiki文档](https://github.com/learnhard-cn/vClash/wiki/%E4%BD%BF%E7%94%A8vClash%E7%94%A8%E6%88%B7%E5%8F%8D%E9%A6%88%E7%9A%84%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93#%E5%8E%9F%E5%9B%A0%E5%88%86%E6%9E%90%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95)
