### ISSUE TITLE
 2022年09月04日23:31:57: 启动配置文件 /koolshare/clash/config.yaml : 检测完毕! 2022年09月04日23:32:00: clash -d /koolshare/clash/ 启动失败! 执行失败原因如下: /koolshare/bin/clash: line 1: syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by cary03** [learnhard-cn/vClash#21]
**Bug描述**
描述遇到的Bug现象，比如 我自己的Yaml格式订阅源无法在"更新管理"的订阅源URL更新。

**Bug重现**
描述触发Bug的步骤:
1. 访问 '...' 页面
2. 点击 '...' tab页面
3. 点击 '...' 功能
4. Bug出现了。

**截图**
如果可以，请附上截图，截图记得将敏感信息打上马赛克。

**路由器信息:**
您可以将 **路由器信息**按钮显示的内容粘帖在这里，以便于我们针对您的路由器出现问题进行定位与修复。

您可以手工填写如下信息:
 - 路由器型号: '...' 例如 RT-AC88U
 - 固件类型: '...' 例如 Koolcenter_华硕官改/Koolcenter_梅林改版等
 - 固件版本: '...' 例如 380/384/386等。
 - 使用的浏览器: '...' 例如 Chrome/Firefox等。

**Comment by cary03** [comment]
`
2022年09月04日23:31:57: 启动配置文件 /koolshare/clash/config.yaml : 检测完毕!
2022年09月04日23:32:00: clash -d /koolshare/clash/ 启动失败! 执行失败原因如下:
/koolshare/bin/clash: line 1: syntax error: unexpected word (expecting ")")`

路由器型号RT-AX86U 固件版本：386 浏览器：chrome

**Comment by Awkee** [comment]
#19 跟这个一样，是不是更新clash之后出现的问题？
