### ISSUE TITLE
停止使用该项目：请不要添加自己私人订阅链接

### ISSUE THREAD

**Issue by Fuuuuuu502** [learnhard-cn/vClash#22]
请不要添加自己私人订阅链接，该项目会上传订阅链接并且分享

**Comment by Awkee** [comment]
呵呵。。。 代码都开源了，请拿出你说话的证据! 哪行代码里有上传订阅链接的功能呢？ 

连我自己都不知道。。。

你是第一个质疑本项目的人，欢迎来质疑，但拿出证据来，希望拿出证据来，否则，我怀疑你是不怀好意的Guy！

**Comment by crazyn2** [comment]
是的，证据在哪里
