### ISSUE TITLE
请问下这个是怎么使用的？

### ISSUE THREAD

**Issue by kyuranger** [learnhard-cn/vClash#23]
路由器是华硕AC-66U B1，刷了最新的梅林固件，装的VClash是ksmerlin386华硕官改、梅林386版本。
装了Github首页的最新版，安装没问题，能运行。
主面板那里不太明白模式选择里面黑名单和白名单有什么不同，看到Github首页动画设置的是白名单，也跟着设白名单了。
看到首页提示说【只需要更新内部提供的 代理节点订阅源即可使用。】
可是找不到代理节点订阅源，于是就点了节点管理那里，把订阅地址填到更新DIY组那里，提交了以后看到删除节点那里有一些节点，应该就是添加成功了。
然后也没法选哪个节点，也不知道要怎么才能弄下去了……
![image](https://user-images.githubusercontent.com/30720036/191967500-ba9d2485-bb3c-479e-bf50-52f5f0fe7acd.png)
有没有教程或者其他什么……现在没法用……

**Comment by Awkee** [comment]
强烈建议看下wiki文档  [黑白名单介绍](https://github.com/learnhard-cn/vClash/wiki#003%E9%85%8D%E7%BD%AEvclash-%E9%BB%91%E5%90%8D%E5%8D%95%E7%99%BD%E5%90%8D%E5%8D%95%E8%A7%84%E5%88%99)

**Comment by zzy-life** [comment]
> 强烈建议看下wiki文档 [黑白名单介绍](https://github.com/learnhard-cn/vClash/wiki#003%E9%85%8D%E7%BD%AEvclash-%E9%BB%91%E5%90%8D%E5%8D%95%E7%99%BD%E5%90%8D%E5%8D%95%E8%A7%84%E5%88%99)

怎么没有节点管理？
![image](https://github.com/vxiaov/vClash/assets/68179477/c4f9843f-79d2-480b-9586-a5f6b2fd41d5)

**Comment by Awkee** [comment]
@zzy-life 节点管理页面在新版本中已经去掉很久了，节点管理需要自己编辑 配置文件解决。
