### ISSUE TITLE
能否提供一个手动安装的教程？

### ISSUE THREAD

**Issue by eromoe** [learnhard-cn/vClash#28]
用的梅林官方386, 想问一下怎么安装这个插件

**Comment by Awkee** [comment]
可以先阅读一下 wiki 文档，路由器离线安装插件方法应该不用介绍了吧？^_^!

**Comment by eromoe** [comment]
后面搜了下才知道都是用koolshare 改版的，我是想问原版meilin咋装。 iptables 这种不太懂
因为几年前装过koolshare 的版本 出了些问题，所以一直是原版meilin

**Comment by Awkee** [comment]
嗯，这个插件是需要先安装 koolshare 软件中心才可以使用的。  https://fw.koolcenter.com/  这里是官方发布的固件地址，需要的话自己研究研究吧。
