### ISSUE TITLE
改了非法字符的变量内容，reboot后还是不能安装

### ISSUE THREAD

**Issue by solerzhuxy** [learnhard-cn/vClash#29]
通过shell把非法字符变量的字符串改成了xxxx，但上传后点击安装没有反应，不能安装，还要什么办法解决呢？
点击后很久出现如下提示：
【2022年12月07日 17:41:39】: ========================== step 1 ===============================
【2022年12月07日 17:41:39】: 开启插件离线安装！
【2022年12月07日 17:41:39】: 检测到你上传的离线安装包：2.tar.gz，安装包大小: 10.2M
【2022年12月07日 17:41:39】: 安装包md5sum校验值：187b64d545fcc5ad6c878cf59b36ef04
【2022年12月07日 17:41:39】: 尝试解压离线安装包离线安装包...
【2022年12月07日 17:41:40】: 安装包解压成功！继续！
【2022年12月07日 17:41:40】: **没有找到插件的web页面！**
【2022年12月07日 17:41:40】: **你上传的文件可能不是koolcenter软件中心离线安装包！**
【2022年12月07日 17:41:40】: 退出本次离线安装！
【2022年12月07日 17:41:40】: 删除文件夹-1：/tmp/2
【2022年12月07日 17:41:40】: 删除文件：/tmp/2.tar.gz
【2022年12月07日 17:41:40】: ============================ end ================================

环境如下：
AC86U, Firmware 386.3, 
KoolCenter v1.9.0.6.

************ 更新进展***********
即使有上面的错误提示，点击安装没有反应，尝试多次后看已安装，居然已经安装好了。不清楚是什么原因导致的。

**Comment by Awkee** [comment]
koolcenter版本我没研究过， 根据你这个错误信息找到下面这段代码：

[代码来源地址](https://github.com/koolshare/rogsoft/blob/3ef3015c3904b80d4afb632d8324650f870b481b/softcenter/softcenter/scripts/ks_tar_install.sh#L193)
```
	# 11. some package not come from koolcenter
	if [ ! -f "/tmp/${MODULE_NAME}/webs/Module_${MODULE_NAME}.asp" -a "${MODULE_NAME}" != "softcenter" ];then
		# 插件必须有web页面，没有则不合规
		echo_date "没有找到插件的web页面！"
		echo_date "你上传的文件可能不是koolcenter软件中心离线安装包！"
		echo_date "退出本次离线安装！"
		exit_tar_install 1
	fi
```

这段代码逻辑是有问题，按这个逻辑 ， 离线安装包就不能乱改名字了，必须与 Module_clash.asp 中的  clash 部分一致，也就是只能是 clash.tar.gz ，否则就会出现你这个错误。
