### ISSUE TITLE
找不到软件中心版本信息！你确定这是KS梅林固件?

### ISSUE THREAD

**Issue by crazyn2** [learnhard-cn/vClash#31]
**Bug描述**
描述遇到的Bug现象，比如 我自己的Yaml格式订阅源无法在"更新管理"的订阅源URL更新。
找不到软件中心版本信息！你确定这是KS梅林固件?
**Bug重现**
描述触发Bug的步骤:
1. 安装tar.gz包

**截图**
如果可以，请附上截图，截图记得将敏感信息打上马赛克。

**路由器信息:**
您可以将 **路由器信息**按钮显示的内容粘帖在这里，以便于我们针对您的路由器出现问题进行定位与修复。
```
【2022年12月31日 19:47:54】: ====================== step 1 ===========================
【2022年12月31日 19:47:54】: 开启软件离线安装！
【2022年12月31日 19:47:54】: /tmp目录下检测到上传的离线安装包clash.tar.gz，大小：12.7M
【2022年12月31日 19:47:54】: 尝试解压离线安装包离线安装包
【2022年12月31日 19:47:56】: 解压完成！
【2022年12月31日 19:47:56】: 准备安装clash插件！
【2022年12月31日 19:47:56】: 找到安装脚本！
【2022年12月31日 19:47:56】: 运行安装脚本...
【2022年12月31日 19:47:56】: ====================== step 2 ===========================
2022年12月31日19:47:57:clash: 梅林固件版本： 380
2022年12月31日19:47:57:clash: 找不到软件中心版本信息！你确定这是KS梅林固件?
【2022年12月31日 19:47:57】: 因为clash插件安装失败！退出离线安装！
【2022年12月31日 19:47:57】: ======================== end ============================
 ```
XU6J03M6
您可以手工填写如下信息:
 - 路由器型号: R8000
 - 固件类型: Koolcenter_梅林改版
 - 固件版本: 380.70_0-X7.9.1
 - 使用的浏览器:Firefox
下载链接: https://github.com/learnhard-cn/vClash/raw/main/release/clash.tar.gz

**Comment by Awkee** [comment]
这个错误是在路由器上执行`dbus get softcenter_version`命令没有获取到软件中心的版本信息。

如果可以ssh登录到路由器上，可以手工执行以下这个命令看看实际情况。

这个380版本固件基本上不更新了（用的人不多）。
