### ISSUE TITLE
华硕AX5400安装后日志总是显示超时，是我使用姿势不对吗大佬？

### ISSUE THREAD

**Issue by buchixiangcai978** [learnhard-cn/vClash#32]
![image](https://user-images.githubusercontent.com/123281873/213898274-b44b9bb9-f873-4b7a-81aa-ad951137c3f7.png)

![image](https://user-images.githubusercontent.com/123281873/213898249-7e80126b-f780-427d-a5c7-bb28fa22f9bf.png)

**Comment by Awkee** [comment]
你这个情况应该是上不去外网了吧？

说明下面情况：
1. 关闭vClash插件是否能上网？
2. 是否开启了其他科学上网工具？
3. iptables规则发一下：方法点击**路由信息**按钮即可获取。
