### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by 1109Hq** [learnhard-cn/vClash#34]
**路由器信息:**
 - 路由器型号: '...' RT-Ax86U
 - 固件类型: '...' Koolcenter_梅林改版
 - 固件版本: '...' Merlin 386.3
安装不上去，求大佬看看什么情况
<img width="592" alt="微信图片_20230202215259" src="https://user-images.githubusercontent.com/90536633/216343449-4764003f-dfa2-45cc-a84a-e5989b19da32.png">

**Comment by Awkee** [comment]
你刷的固件哪里来的？ 显示错误 找不到 /koolshare/init.d 目录，这个目录正常是必须存在的呀。
