### ISSUE TITLE
无法更新以及找不到订阅节点

### ISSUE THREAD

**Issue by mikeltr01** [learnhard-cn/vClash#36]
感谢开发者使我可以翻墙回国，一直用的好好的，今天突然有些问题，还望给予指点，非常非常感谢！
1. 翻不了墙了我发现clash从我的梅林软件中心被抹去了，重装clash后成功添加节点订阅，但是看不到也无法选择具体的线路
2. 无法更新clash，主面板和以前也不一样，我记得之前会显示联网状态，现在什么都没有了。
3. 无法打开yacd控制面板
请查看附件截屏。

您的路由器基本信息(反馈开发者帮您分析问题用):
| system : Linux RT-AC66U_B1-35B8 2.6.36.4brcmarm armv7l ASUSWRT-Merlin-KoolShare|
| rom    : RT-AC68U:koolshare梅林改版固件:386.7|
| memory : free: 157.42 MB,total: 249.72 MB,usage:  36.96%|
| /jffs  : free:  44.72 MB,total:  62.75 MB,usage:  28.74%|
+---------------------------------------------------------------+
|>> vClash当前正在使用的软件版本:                                   << |
|              vClash :                                         |
|       clash_premium : 2021.09.15_linux_arm                    |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5rc2-245-g7b81a83-dirty            |
|>> vClash初始安装包自带的软件版本(分析是否个人更改过):                                   << |
|              vClash : v2.2.19                                 |
|       clash_premium : 2021.09.15_v1.7.1                       |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5rc2-245-g7b81a83-dirty            |
+---------------------------------------------------------------+
vClash的转发规则(iptables -t nat -S | grep clash),分析转发规则是否正常:
+---------------------------------------------------------------+
 
![Screenshot 2023-05-01 150155](https://user-images.githubusercontent.com/132253011/235420287-46c6d586-c78e-4a32-8be2-440939b698bf.png)
![Screenshot 2023-05-01 150248](https://user-images.githubusercontent.com/132253011/235420290-6921a6e8-88ab-4a70-8bf4-25d9f4ae390c.png)

**Comment by Awkee** [comment]
@mikeltr01 反馈收到，在线更新clash失败了，可以可选功能中找到本地上传更新。
这个版本一直没有添加连接状态检查功能的(没必要检测，直接打开网页就可以验证的，干嘛要暴漏自己的地址给那些IP检测平台)，可能你将这个插件跟其他插件弄混淆了。

**Comment by mikeltr01** [comment]
是的 记错了
