### ISSUE TITLE
support AX86U

### ISSUE THREAD

**Issue by zhudan** [learnhard-cn/vClash#4]
did you have plan too support AX86U？

**Comment by Awkee** [comment]
可以，有时间我再参考其他ax86u插件逻辑适配一下，但没真机测试，可能实际使用还需要反馈使用情况完善。

**Comment by luogencao** [comment]
> 可以，有时间我再参考其他ax86u插件逻辑适配一下，但没真机测试，可能实际使用还需要反馈使用情况完善。

所以当前不支持AX86U咯？希望添加呀

**Comment by Awkee** [comment]
Koolcenter上是这样写的：

> RT-AX86U属于p1axhnd.675平台机型，对于hnd/axhnd/axhnd.675/p1axhnd.675平台机型，使用的是rogsoft软件中心，这些机型的插件是可以通用的。

也就是说，我写的插件理论上适用AX86U，如果有什么问题也是逻辑检测问题。由于本人没有`RT-AX86U机型`路由器，因此没法实测效果。

有需要使用的此插件的朋友，可以联系我[TG电报联系地址](https://t.me/vlikework)，协助安装适配。

**Comment by Awkee** [comment]
有朋友实测是可以在RT-AX86U上用的。

大家可以多尝试，有问题反馈问题，暂时可以先卸载了，等问题解决了再使用。
