### ISSUE TITLE
vClash2.1.1 ax88u merlin386.2

### ISSUE THREAD

**Issue by mm1327** [learnhard-cn/vClash#5]
【2021年12月23日 23:02:28】: ========================== step 1 ===============================
【2021年12月23日 23:02:28】: 开启插件离线安装！
【2021年12月23日 23:02:28】: 检测到你上传的离线安装包：vclash-2.1.1.tar.gz，安装包大小: 14.2M
【2021年12月23日 23:02:28】: 安装包md5sum校验值：1f2658c3f29686d9e9516e09bf2973b2
【2021年12月23日 23:02:28】: 尝试解压离线安装包离线安装包...
【2021年12月23日 23:02:29】: 安装包解压成功！继续！
【2021年12月23日 23:02:29】: 没有找到插件的web页面！
【2021年12月23日 23:02:29】: 你上传的文件可能不是koolcenter软件中心离线安装包！
【2021年12月23日 23:02:29】: 退出本次离线安装！
【2021年12月23日 23:02:29】: 删除文件夹-2：/tmp/vClash-2.1.1
【2021年12月23日 23:02:30】: 删除文件：/tmp/vclash-2.1.1.tar.gz
【2021年12月23日 23:02:30】: ============================ end ================================
update merlin version is 386.3_2
请问怎么解 谢谢

![image](https://user-images.githubusercontent.com/20600090/147259214-a017a7ca-4263-44b6-b1f0-7763e23ca480.png)

**Comment by Awkee** [comment]
这个错误逻辑如下：
```bash
	# 11. some package not come from koolcenter
	if [ ! -f "/tmp/${MODULE_NAME}/webs/Module_${MODULE_NAME}.asp" -a "${MODULE_NAME}" != "softcenter" ];then
		# 插件必须有web页面，没有则不合规
		echo_date "没有找到插件的web页面！"
		echo_date "你上传的文件可能不是koolcenter软件中心离线安装包！"
		echo_date "退出本次离线安装！"
		exit_tar_install 1
	fi
```
根据你错误信息`删除文件夹-2：/tmp/vClash-2.1.1`来看，是目录检查规则问题。

## 解决办法

如果目录名为`/tmp/clash`，也就是把压缩包文件名改为`/tmp/clash.tar.gz`就可以了。

这个是我把项目名由原来的`clash`改成了`vClash`后，github自动生成的压缩包名称就这样了。

**Comment by Awkee** [comment]
为了方便获取最新安装包，更新了一下项目目录结构，可以在`release`目录获取不同分支的安装包文件,保证了文件名`clash.tar.gz`
