### ISSUE TITLE
控制台中可以看到流量在跑，但是客户端没有效果

### ISSUE THREAD

**Issue by mrbruce516** [learnhard-cn/vClash#6]
自己写的配置文件，主要就是加了proxies和重写了rules部分，其他未动。
![image](https://user-images.githubusercontent.com/46187947/148637461-b138f3f9-5bf4-485b-8121-3cc8ac629009.png)
![image](https://user-images.githubusercontent.com/46187947/148637465-be3266a3-3a90-4328-bb5b-63e44ce09e55.png)
![image](https://user-images.githubusercontent.com/46187947/148637472-a2552a3e-5624-449d-977e-235b41ffee87.png)

**Comment by mrbruce516** [comment]
release v2.0.6 版本无此问题，自定义config文件可正常使用

**Comment by Awkee** [comment]
Yacd页面可以看到流量了，说明已经流量转发正常，"客户端没效果"是访问页面没走指定规则么？还是没有看到连接信息？


默认情况下"可选配置" => "启用黑名单模式(建议关闭):" 选择关闭，这样才能代理全部的内网请求，如果开启了只会转发匹配gfwlist.conf中的url规则请求。

v2.0.6版本没问题就好，你说的信息太少，没办法帮你分析“没效果”的原因。再遇到问题，可以详细描述下，比如 访问youtube 在Yacd看不到连接信息。

通常vClash的透明代理功能正常，其它问题就看配置文件了。
