### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wac81** [learnhard-cn/vClash#7]
INFO[0000] Start initial provider provider_free         
INFO[0000] Start initial provider provider_outwall      
INFO[0000] Start initial provider provider_netflix      
INFO[0000] Start initial provider provider_home_netflix 
INFO[0000] Start initial provider provider_url          
INFO[0000] Start initial provider provider_diy          
FATA[0000] Parse config error: initial proxy provider provider_diy error: file doesn't have any proxy

**Comment by Awkee** [comment]
这是文件provider_diy.xml 文件缺失，复制 provider_free.xml 文件内容即可。
