### ISSUE TITLE
want to support k3c(mips)

### ISSUE THREAD

**Issue by QiuWeimengChan** [learnhard-cn/vClash#8]
linux core 3.10.104
cpu grx500
MerlinR 5.0.0+

toolchian:https://github.com/SWRT-dev/softcenter_tools

**Comment by Awkee** [comment]
clash有mips版本，你自己更新一下clash可执行文件试试。没有实际路由器测试，开发起来就很难。

**Comment by QiuWeimengChan** [comment]
> 

好的，谢谢
