### ISSUE TITLE
华硕ac86u 386 版本离线安装后启动报错

### ISSUE THREAD

**Issue by Langni** [learnhard-cn/vClash#9]
admin@RT-AC86U-2410:/jffs/.koolshare/clash/providers# clash -d /koolshare/clash/
INFO[0000] Start initial provider provider_netflix      
INFO[0000] Start initial provider provider_home_netflix 
INFO[0000] Start initial provider provider_url          
INFO[0000] Start initial provider provider_diy          
FATA[0000] Parse config error: initial proxy provider provider_diy error: file doesn't have any proxy

**Comment by Langni** [comment]
这是配置文件
admin@RT-AC86U-2410:/jffs/.koolshare/clash/providers# vi provider_remote.yaml 

proxies:
- name: test-vlike.work
  type: ss
  server: 176.125.231.3
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6

**Comment by Awkee** [comment]
提示信息的意思是缺少 provider_diy 订阅源文件，应该对应的是`provider_diy.yaml`文件，复制一个 provider_remote.yaml 文件就可以了。
